[package]
name = "plegosa"
version = "0.1.0"
authors = ["SyoBoN <syobon@syo.bar>"]
edition = "2021"
description = "A simple Egosa (ego-search) tool for Pleroma"
repository = "https://github.com/syobocat/plegosa/"
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
megalodon = { version = "0.11" }
tokio = { version = "1" }
log = { version = "0.4" }
env_logger = { version = "0.10" }
dotenvy = { version = "0.15" }
ureq = { version = "2", features = ["json"] }
nanohtml2text = { version = "0.1" }
kanaria = { version = "0.2" }
lexical_bool = { version = "0.1" }
regex = { version = "1" }

[target.x86_64-unknown-linux-musl.dependencies]
openssl = { version = "0.10", features = ["vendored"] }

[target.x86_64-unknown-netbsd.dependencies]
openssl = { version = "0.10", features = ["vendored"] }

# Workaround for #11

[package.metadata.cross.target.x86_64-unknown-netbsd]
pre-build = [
    "mkdir -p /tmp/netbsd",
    "curl https://cdn.netbsd.org/pub/NetBSD/NetBSD-9.2/amd64/binary/sets/base.tar.xz -O",
    "tar -C /tmp/netbsd -xJf base.tar.xz",
    "cp /tmp/netbsd/usr/lib/libexecinfo.so /usr/local/x86_64-unknown-netbsd/lib",
    "rm base.tar.xz",
    "rm -rf /tmp/netbsd",
]
